[package]
name = "pestvsantlr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2"
pest_derive = "2"
pest_grammars = "2.6.0"

[build-dependencies]
cmake = "0.1.50"
